source "https://rubygems.org"

gem 'rspec'
gem 'capybara', require: false
gem 'selenium-webdriver', require: false
gem 'pry', require: false
gem 'launchy'
gem 'capybara-screenshot', require: false
gem 'database_cleaner'