require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContactsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Contact. As you add validations to Contact, be sure to
  # adjust the attributes here as well.
  let(:sc_marti) { SchemeOperator.new }
  before do
    sc_marti.email = 'jennifer@back_to_the_future.com'
    sc_marti.first_name = 'Jennifer'
    sc_marti.last_name = 'Smith'
    sc_marti.password = 'mypassword'
    sc_marti.confirmed_at = DateTime.now
    sc_marti.schemes = [Scheme.first]
    sc_marti.save
    sc_marti.approved = true
    sc_marti.save
    sc_marti.add_role :sc_director

    PermissionsForRole::SchemeOperatorDefinitions.new.permissions_for_role(:sc_director).each do |permission, has|
      sc_marti.add_role permission if has[:checked]
    end
    sc_marti.contacts_d!
    sign_in sc_marti
  end

  after do
    sign_out sc_marti
  end

  let(:valid_attributes) do
    {
      address_type_id: 2,
      business_id:     1,
      first_name:      'nigel',
      last_name:       'surtees',
      title:           'Mr',
      email:           'somebody@emai.com',
      telephone_1:     '09876543212',
      telephone_2:     '09876543233',
      fax:             '987864357389485'
    }
  end

  let(:invalid_attributes) do
    {
      address_type_id: 2,
      business_id:     1,
      first_name:      nil,
      last_name:       'surtees',
      title:           'Mr',
      email:           'somebody@emai.com',
      telephone_1:     '09876543212',
      telephone_2:     '09876543233',
      fax:             '987864357389485'
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all contacts as @contacts' do
      contact = Contact.create! valid_attributes
      get :index, business_id: 1, session: valid_session

      contacts = assigns(:contacts)
      retrieved_contact = contacts.where(id: contact.id)
      expect(retrieved_contact).to eq([contact])
    end

    it 'assigns business as @business' do
      get :index, business_id: 1, session: valid_session

      business = assigns(:business)
      expect(business.id).to eq(1)
    end
  end

  describe 'GET #show' do
    it 'assigns the requested contact as @contact' do
      contact = Contact.create! valid_attributes
      get :show, id: contact.to_param, business_id: 1, session: valid_session
      expect(assigns(:contact)).to eq(contact)
    end
  end

  describe 'GET #new' do
    it 'assigns a new contact as @contact' do
      get :new, business_id: 1, session: valid_session
      expect(assigns(:contact)).to be_a_new(Contact)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested contact as @contact' do
      contact = Contact.create! valid_attributes
      get :edit, id: contact.to_param, business_id: 1, session: valid_session
      expect(assigns(:contact)).to eq(contact)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Contact' do
        expect do
          post :create, contact: valid_attributes, business_id: 1, session: valid_session
        end.to change(Contact, :count).by(1)
      end

      it 'assigns a newly created contact as @contact' do
        post :create, contact: valid_attributes, business_id: 1, session: valid_session
        expect(assigns(:contact)).to be_a(Contact)
        expect(assigns(:contact)).to be_persisted
      end

      it 'redirects to the created contact' do
        post :create, contact: valid_attributes, business_id: 1, session: valid_session
        expect(response).to redirect_to(business_contact_path(id: Contact.last.id))
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved contact as @contact' do
        post :create, contact: invalid_attributes, business_id: 1, session: valid_session
        expect(assigns(:contact)).to be_a_new(Contact)
      end

      it "re-renders the 'new' template" do
        post :create, contact: invalid_attributes, business_id: 1, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested contact' do
        contact = Contact.create! valid_attributes
        put :update, id: contact.to_param, contact: new_attributes, business_id: 1, session: valid_session
        contact.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested contact as @contact' do
        contact = Contact.create! valid_attributes
        put :update, id: contact.to_param, contact: valid_attributes, business_id: 1, session: valid_session
        expect(assigns(:contact)).to eq(contact)
      end

      it 'redirects to the contact' do
        contact = Contact.create! valid_attributes
        put :update, id: contact.to_param, contact: valid_attributes, business_id: 1, session: valid_session
        expect(response).to redirect_to(business_contact_path(id: contact.id))
      end
    end

    context 'with invalid params' do
      it 'assigns the contact as @contact' do
        contact = Contact.create! valid_attributes
        put :update, id: contact.to_param, contact: invalid_attributes, business_id: 1, session: valid_session
        expect(assigns(:contact)).to eq(contact)
      end

      it "re-renders the 'edit' template" do
        contact = Contact.create! valid_attributes
        put :update, id: contact.to_param, contact: invalid_attributes, business_id: 1, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested contact' do
      contact = Contact.create! valid_attributes
      expect do
        delete :destroy, id: contact.to_param, business_id: 1, session: valid_session
      end.to change(Contact, :count).by(-1)
    end

    it 'redirects to the contacts list' do
      contact = Contact.create! valid_attributes
      delete :destroy, id: contact.to_param, business_id: 1, session: valid_session
      expect(response).to redirect_to(business_contacts_path(business_id: 1))
    end
  end
end
